# Generated by Django 5.1.1 on 2025-04-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_sozlamalar_bildirishnoma_yoqilgan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozlamalar',
            name='bildirishnoma_yoqilgan',
            field=models.CharField(choices=[('Yes', 'Ha'), ('Uzbek', 'Uzbek'), ('Rus', 'Rus'), ('English', 'English')], default=True, max_length=15),
        ),
    ]
